language: java
sudo: false
install: true
before_install:
  - chmod +x mvnw
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
notifications:
  email: false
addons:
  sonarcloud:
    organization: "rashidi-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar